# Assignment

### 1. create an random array of shape (6x6)
### 2. convert the array to an identity matrix

In [2]:
def array_properties(a, label='a'):
    print(label, '= ')
    print(a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

In [4]:
import numpy as np

np.random.seed(2)

a = np.random.randint(0,20,(6,6))
array_properties(a, 'a')

a = 
[[ 8 15 13  8 11 18]
 [11  8  7  2 17 11]
 [15  5  7  3  6  4]
 [10 11 19  7  6 10]
 [ 1  3  5  4 14  6]
 [19  2 16 14 12 18]]
dim =  2
shape =  (6, 6)
datatype =  int32
size =  36



In [5]:
a[:]=np.identity(6)
array_properties(a, 'a')

a = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
dim =  2
shape =  (6, 6)
datatype =  int32
size =  36

