# Assignment 7 boolean and split

In [1]:
# 1. Create an array of shape (100,100,3) of unisigned integer 8 bits
#    fill with random values between 0-256.
# 2. Find the values that are less than 30,50,100,250.
# 3. Split the array into 4 parts vertically and horizontally.
# 4. Copy array from question 1 and change the values that are 
#    less than 118 to 0 and others to 255.
# 5. Hint use random seed of 12345

In [1]:
def array_properties(a):
    print("a = \n", a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

In [107]:
#question 1 & 5

import numpy as np

np.random.seed(12345)

a1 = np.random.randint(0,256,(100,100,3),dtype='uint8')
array_properties(a1)

a = 
 [[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195]
  [ 57  77 233]
  [  7 230   8]
  ...
  [ 64 151 156]
  [202  15 104]
  [221 112 230]]

 ...

 [[ 61 149 122]
  [ 60 176 204]
  [102  45  44]
  ...
  [136 101 177]
  [ 42 177 221]
  [138 102  84]]

 [[120  73 190]
  [175  32  56]
  [211 192 194]
  ...
  [239 223  11]
  [ 46   7 253]
  [ 35 125 235]]

 [[212 239  76]
  [ 92 178 105]
  [ 90 242 147]
  ...
  [213 192  46]
  [198 244 112]
  [156 214 199]]]
dim =  3
shape =  (100, 100, 3)
datatype =  uint8
size =  30000



In [11]:
#2.
iboolles30 = a1 <= 30 
iboolles50 = a1 <= 50 
iboolles100 = a1 <= 100
iboolles250 = a1 <= 250

iboolles30 = iboolles30 == True
iboolles50 = iboolles50 == True
iboolles100 = iboolles100 == True
iboolles250 = iboolles250 == True

les30result = a1[iboolles30]
array_properties(les30result)

les50result = a1[iboolles50]
array_properties(les50result)

les100result = a1[iboolles100]
array_properties(les100result)

les250result = a1[iboolles50]
array_properties(les250result)

a = 
 [29  8 21 ... 30 28 24]
dim =  1
shape =  (3627,)
datatype =  uint8
size =  3627

a = 
 [45 29  8 ... 35 24 46]
dim =  1
shape =  (5980,)
datatype =  uint8
size =  5980

a = 
 [81 45 29 ... 75 24 46]
dim =  1
shape =  (11978,)
datatype =  uint8
size =  11978

a = 
 [45 29  8 ... 35 24 46]
dim =  1
shape =  (5980,)
datatype =  uint8
size =  5980



In [91]:
#4.
newa1=a1.copy()
array_properties(newa1)
print(newa1)

a = 
 [[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195]
  [ 57  77 233]
  [  7 230   8]
  ...
  [ 64 151 156]
  [202  15 104]
  [221 112 230]]

 ...

 [[ 61 149 122]
  [ 60 176 204]
  [102  45  44]
  ...
  [136 101 177]
  [ 42 177 221]
  [138 102  84]]

 [[120  73 190]
  [175  32  56]
  [211 192 194]
  ...
  [239 223  11]
  [ 46   7 253]
  [ 35 125 235]]

 [[212 239  76]
  [ 92 178 105]
  [ 90 242 147]
  ...
  [213 192  46]
  [198 244 112]
  [156 214 199]]]
dim =  3
shape =  (100, 100, 3)
datatype =  uint8
size =  30000

[[[226  81 251]
  [237 229  45]
  [225 227  29]
  ...
  [152 224 239]
  [147 249 235]
  [ 22  77  13]]

 [[  5 116 247]
  [167  74 150]
  [ 36 229  76]
  ...
  [ 85 171 127]
  [  1 129 245]
  [243  42  21]]

 [[192  98 195]
  [ 57  77 233]
  [  7 230   8]
  ...
  [ 64 151 156]
  [202  15 104]
  [22

In [120]:
ibool180 = newa1 <=180
array_properties(ibool180)

iboolles180 = ibool180 == True 
iboolmore180 = ibool180 == False 

newa1[iboolles180]=0
newa1[iboolmore180]=255

array_properties(newa1)

a = 
 [[[False  True False]
  [False False  True]
  [False False  True]
  ...
  [ True False False]
  [ True False False]
  [ True  True  True]]

 [[ True  True False]
  [ True  True  True]
  [ True False  True]
  ...
  [ True  True  True]
  [ True  True False]
  [False  True  True]]

 [[False  True False]
  [ True  True False]
  [ True False  True]
  ...
  [ True  True  True]
  [False  True  True]
  [False  True False]]

 ...

 [[ True  True  True]
  [ True  True False]
  [ True  True  True]
  ...
  [ True  True  True]
  [ True  True False]
  [ True  True  True]]

 [[ True  True False]
  [ True  True  True]
  [False False False]
  ...
  [False False  True]
  [ True  True False]
  [ True  True False]]

 [[False False  True]
  [ True  True  True]
  [ True False  True]
  ...
  [False False  True]
  [False False  True]
  [ True False False]]]
dim =  3
shape =  (100, 100, 3)
datatype =  bool
size =  30000

a = 
 [[[255   0 255]
  [255 255   0]
  [255 255   0]
  ...
  [  0 255 255]
  [  0 2

In [116]:
#3.
a1_hsp = np.hsplit(a1,4)
print(a1_hsp)

[array([[[ 95, 113,  61],
        [177,  45,  42],
        [ 40, 129, 137],
        ...,
        [ 55,  25,  79],
        [ 92,  29, 191],
        [199, 102,   4]],

       [[  6, 159, 204],
        [ 91, 231,  10],
        [249,  86, 174],
        ...,
        [ 65, 175,  35],
        [ 96,  38,  45],
        [206, 148, 224]],

       [[230, 248, 162],
        [156,  66,  16],
        [192, 177, 107],
        ...,
        [171, 174, 136],
        [ 95, 233,  96],
        [113,  73, 165]],

       ...,

       [[187, 120, 192],
        [136,  97, 230],
        [107,  29, 116],
        ...,
        [ 24, 248, 129],
        [ 83, 163, 110],
        [119, 120, 178]],

       [[111,  73,  90],
        [251,  23, 161],
        [232, 164,  13],
        ...,
        [146,  45, 180],
        [ 52, 108,  68],
        [ 10, 193, 117]],

       [[ 37, 131, 204],
        [136, 166, 170],
        [179,  66, 194],
        ...,
        [ 44, 168,  59],
        [156,  98, 224],
        [133, 122, 127]

In [117]:
len(a1_hsp)

4

In [118]:
a1_vsp = np.vsplit(a1,4)
print(a1_vsp)

[array([[[ 95, 113,  61],
        [177,  45,  42],
        [ 40, 129, 137],
        ...,
        [198,  44, 184],
        [237, 244,  72],
        [ 79, 204, 120]],

       [[  6, 159, 204],
        [ 91, 231,  10],
        [249,  86, 174],
        ...,
        [120,  54,  72],
        [112, 242, 209],
        [155, 119, 137]],

       [[230, 248, 162],
        [156,  66,  16],
        [192, 177, 107],
        ...,
        [ 25,  58, 211],
        [196, 138, 227],
        [170, 125, 121]],

       ...,

       [[ 30,  13,  26],
        [103, 181,  24],
        [175, 254, 111],
        ...,
        [222,  37, 138],
        [231,  67, 206],
        [129, 204,  57]],

       [[148,  96, 185],
        [ 56, 207, 252],
        [248, 118, 158],
        ...,
        [170,  85, 217],
        [241, 217, 110],
        [118, 203, 250]],

       [[ 53, 156, 175],
        [128,  63,  12],
        [240,  17, 228],
        ...,
        [106,  73, 215],
        [121,  99, 188],
        [ 75, 172,  70]

In [119]:
len(a1_vsp)

4